name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Verify Python
      run: python --version

    # ✅ FIXED Docker Build (NO slash issue)
    - name: Build Docker Image
      run: docker build -t varshithchand/flask-website .

    # ✅ Login to DockerHub
    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "varshithchand" --password-stdin

    # ✅ Push Image
    - name: Push Docker Image
      run: docker push varshithchand/flask-website
